project:
  type: website

website:
  page-navigation: true
  title: "AMLOB"
  site-url: "https://social-oceans-lab.github.io/social-indicators-project/"
  repo-url: https://github.com/Social-Oceans-Lab/social-indicators-project
  navbar:
    title: false
    background: light
    logo: "images/collab_logo.png"
    logo-alt: "Official logos of the University of Maine, Maine Department of Marine Resources, Maine Lobstermen's Association, and the Maine Center for Coastal Fisheries"
    right:
      - text: "Home"
      - file: index.qmd
      - methods.qmd
      - results.qmd
      - text: "Data Access"
      - file: data-access.qmd
      - text: "Contact"
  page-footer:
    background: light
    right: "This page is built using [Quarto](https://quarto.org/)."
    left: "&copy; Univeristy of Maine, 2023"

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


