project:
  type: website

website:
  #page-navigation: true
  title: "American Lobster Fishery Social Indicators Project"
  site-url: "https://social-oceans-lab.github.io/social-indicators-project/"
  repo-url: https://github.com/Social-Oceans-Lab/social-indicators-project
  navbar:
    title: "American Lobster Fishery Social Indicators Project"
    background: light
    search: false
    right:
      - text: "Home"
        file: index.qmd
      - text: "Indicators"
        file: results.qmd
      - methods.qmd
      - text: "Data Access"
        file: data-access.qmd
      - contact.qmd
  sidebar:
    title: "American Lobster Fishery Social Indicators Project"
    logo: "images/collab_funding_logo.png"
    logo-alt: "Official logos of the University of Maine, Maine Department of Marine Resources, Maine Lobstermen's Association, and the Maine Center for Coastal Fisheries"
  page-footer:
    background: dark
    right: "This page is built using [Quarto](https://quarto.org/)."
    left: "&copy; Univeristy of Maine, 2023"

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


